### ISSUE TITLE
Fields are not being saved

### ISSUE THREAD

**Issue by RamonIrvingAngelo** [formtools/module-extended_client_fields#1]
Hi, I'm trying to add a new field using this module, unfortunately it won't add and the extended client field list remains empty.

**Comment by benkeen** [comment]
Hmm! Bit surprising - this module has functioned perfectly for a long time. I wonder if perhaps you're running a new version of PHP/MySQL and it's no longer entirely compatible. 

I don't suppose it would be possible to get temporary access to your installation so I could debug this? If so, email me at ben.keen@gmail.com.

**Comment by RamonIrvingAngelo** [comment]
Hi Ben, thanks for the reply. Anyway, my installation is in an intranet server so it may be hard for me to give you access to the installation. I tried installing a previously downloaded version of extended_client_fields and it worked.

**Comment by RamonIrvingAngelo** [comment]
Here's the downloaded extended client fileds: 
[extended_client_fields1.2.6.zip](https://github.com/formtools/module-extended_client_fields/files/849465/extended_client_fields1.2.6.zip)

**Comment by benkeen** [comment]
Ah - glad the previous version worked. Thanks! :)
