### ISSUE TITLE
Bug in latest version of module

### ISSUE THREAD

**Issue by Ne0-d3gen** [formtools/module-extended_client_fields#3]
Another bug @benkeen. It appears I can successfully create an extended client field using the module. However, after creating the extended field if I then log in as any user and go to their account information, the new field has not been added. Furthermore if I then go to Users under my admin menu and try to edit any user account I get the following error:

> Fatal error: Uncaught --> Smarty Compiler: Syntax error in template "file:/home/acutemed/warwickacutemedicine.co.uk/acportfolio/modules/extended_client_fields/smarty_plugins/section_html.tpl" on line 45 "{display_option_list option_list_id=$extended_field.option_list_id name="ecf_`$client_field_id`" format="radios"" unknown tag "display_option_list" <-- thrown in /home/acutemed/warwickacutemedicine.co.uk/acportfolio/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatecompilerbase.php on line 45

**Comment by benkeen** [comment]
Hey @tomheaps, sorry for the wait! 

I actually couldn't reproduce the issues you came across, but I did find a couple of other issues while I was testing. The unknown tag of `display_option_list` is very puzzling... that's function is part of the Core. When you run the `file` test in System Check, does it complain at all? (I even checked the other themes to make sure it wasn't a theme problem).

For the missing fields when the user logs in, I'm wondering if perhaps the hooks are incorrect on your system... tell you what, I'll release an update tonight containing a few fixes, plus a new mechanism that resets the hooks after upgrading [I'll be adding this to all modules in preparation for the beta]. 

Ben

**Comment by Ne0-d3gen** [comment]
Thanks @benkeen but no joy with update, still getting the same error message as above. Have run system check for files and hooks and everything has passed fine. Not sure what is going on.....

**Comment by johnbleck3** [comment]
I can confirm - tried it too - same Fatal error System check everything passes.

**Comment by benkeen** [comment]
Huh! The evidence mounts. I'll try a fresh install tomorrow... maybe there's something about my local installation that's allowing it to work.

**Comment by benkeen** [comment]
Thanks! I was able to reproduce it in the end. For some reason my cached smarty files prevented me seeing the error - deleting them caused the error to appear right away. 

I just released 2.0.3 that includes a fix for this.

**Comment by Ne0-d3gen** [comment]
Thanks @benkeen! Now if only there was an upgrade script to make installation of all these updates easier ;)

**Comment by benkeen** [comment]
lol that's what I'll be working on today... :)
